#!/usr/bin/env bash

db_user=$1
db_password=$2

sqlplus / as sysdba <<SQL
CREATE USER $db_user IDENTIFIED BY $db_password DEFAULT TABLESPACE USERS ACCOUNT UNLOCK PROFILE DEFAULT;
GRANT CONNECT, RESOURCE TO $db_user;
GRANT CREATE VIEW TO $db_user;
GRANT CREATE SEQUENCE TO $db_user;
GRANT CREATE SYNONYM TO $db_user;
GRANT CREATE MATERIALIZED VIEW TO $db_user;
GRANT CREATE ANY MATERIALIZED VIEW TO $db_user;
GRANT ALTER ANY MATERIALIZED VIEW TO $db_user;
GRANT SELECT ANY DICTIONARY TO $db_user;
GRANT UNLIMITED TABLESPACE TO $db_user;
GRANT CHANGE NOTIFICATION TO $db_user;
GRANT SELECT ON SYS.DBA_PENDING_TRANSACTIONS TO $db_user;
GRANT EXECUTE ON SYS.DBMS_SYSTEM TO $db_user;
GRANT SELECT ON SYS.PENDING_TRANS$ TO $db_user;
GRANT SELECT ON SYS.DBA_2PC_NEIGHBORS TO $db_user;
GRANT EXECUTE ON SYS.DBMS_XA TO $db_user;
GRANT SELECT ON SYS.DBA_2PC_PENDING TO $db_user;
SQL
